#!/bin/bash
set -eu

if [ "${DOCKER_TAG}" = "latest" ]; then
  VERSION=$(docker run --rm ${IMAGE_NAME} version)
  docker tag ${IMAGE_NAME} ${DOCKER_REPO}:${VERSION}
  docker push ${DOCKER_REPO}:${VERSION}
fi
