name: Publish
on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

permissions: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@7372622e62b60b3cb750dcd2b9e32c247ffec26a # v1.302.0
      - run: bundle install
      - uses: rubygems/release-gem@6317d8d1f7e28c24d28f6eff169ea854948bd9f7 # v1.2.0

  docker-build:
    needs: publish
    permissions:
      contents: read
    uses: ./.github/workflows/docker-build.yml
    with:
      publish: true
    secrets: inherit
