name: Publish
on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

permissions: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@3ff19f5e2baf30647122352b96108b1fbe250c64 # v1.299.0
      - run: bundle install
      - uses: rubygems/release-gem@e9a6361a0b14562539327c2a02373edc56dd3169 # v1.1.4

  docker-build:
    needs: publish
    permissions:
      contents: read
    uses: ./.github/workflows/docker-build.yml
    with:
      publish: true
    secrets: inherit
