name: tagpr
on:
  push:
    branches: ["main"]

permissions: {}

jobs:
  tagpr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: read
    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false
    - uses: ruby/setup-ruby@e65c17d16e57e481586a6a5a0282698790062f92 # v1.300.0
    - run: bundle install
    - uses: Songmu/tagpr@9d0f650553240dab1fa907eca27e3fd5b586e538 # v1.18.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
