name: tagpr
on:
  push:
    branches: ["main"]

permissions: {}

jobs:
  tagpr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: read
    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false
    - uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
    - run: bundle install
    - uses: Songmu/tagpr@555e72cee68c09d43dc2337dc9ba890955b630da # v1.19.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
