name: tagpr
on:
  push:
    branches: ["main"]

permissions: {}

jobs:
  tagpr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: read
    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false
    - uses: ruby/setup-ruby@09a7688d3b55cf0e976497ff046b70949eeaccfd # v1.288.0
    - run: bundle install
    - uses: Songmu/tagpr@da82ed6743aec90049892070edd5561335904a9e # v1.17.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
